### ISSUE TITLE
Replacing enc.c with Snow2 stream cipher

### ISSUE THREAD

**Issue by HatsuneMoe** [regomne/mabi-pack2#1]
.it pack use Snow2 cipher

Snow2 implement: [https://github.com/k0dai/fsbench-density/blob/cb719fdb07354e0c39a255d8d12f3cbd50b44406/src/codecs/ecrypt/snow2_fast.c](https://github.com/k0dai/fsbench-density/blob/cb719fdb07354e0c39a255d8d12f3cbd50b44406/src/codecs/ecrypt/snow2_fast.c)

it could be replaced by this:
c_init_enc_state => snow_loadkey_fast
c_update_enc_state =>  snow_keystream_fast

additional:
snow_loadkey_fast use u32, assembly code would be movzx, it may cause a bad keystream, I think i32 would be correct.

**Comment by regomne** [comment]
Thank you, I will replace it after testing.

I'm curious about how you find the algorithm? I googled some constants but only find Sosemanuk and AES.

**Comment by HatsuneMoe** [comment]
> Thank you, I will replace it after testing.
> 
> I'm curious about how you find the algorithm? I googled some constants but only find Sosemanuk and AES.

Alright, I find that called SnowCipher in some dll.

A rule for cryptographic is
> Don't try to invent your own encryption algorithm or protocol

Considering when they did this packer, i think i could probably find some cipher called snow before 201x.

The absolutely key point is that wired tab, it neither sosemanuk nor AES.

Finally, i find this strange tab in snow2.0, and i made my unpacker which still has some little bugs, my unpacker has some trouble with job.xml, works well for other

**Comment by regomne** [comment]
Thank you for your explanation. I have replaced enc.c with snow2_fast.c and tested OK.
