### ISSUE TITLE
在自己测试时发现了一个诡异的事情:

### ISSUE THREAD

**Issue by cronfox** [regomne/mabi-pack2#2]
我手贱把 https://github.com/regomne/mabi-pack2/blob/7b526038a9742e510042fa1c6e5185b8321728c2/src/snow2.h#L65-L72 改成了 

```
typedef struct
{
  u32 keysize;
  u8 key[32]; /* MODIFIED in Mabinogi, original type is u8 */

  u32 s15, s14, s13, s12, s11, s10, s9, s8, s7, s6, s5, s4, s3, s2, s1, s0;
  u32 r1, r2; 
} Snow2_ctx;

```

然后跑cargo test 直接过了...

我怀疑洛奇可能是直接用了u8(

--------
单元测试正常≠实际测试正常

**Comment by regomne** [comment]
呃，是因为我单元测试没认真写……这里的类型不对的话只会影响“key中存在大于0x7f的字节”时的情况，而我唯一的一个测试用例里面没覆盖这个情况。

晚些时候加上。

**Comment by HatsuneMoe** [comment]
key我觉得是个u8的，snow_loadkey_fast里面的ctx->sn的初始化应该是个signed的，至少我之前这么写的能跑。
snow_loadkey_fast中的ctx的符号后面编译出来的有movsx和movzx的差别，看起来是signed能正确解压，可以试试？

**Comment by regomne** [comment]
加上了测试用例，可以测试一下。

**Comment by cronfox** [comment]
> 加上了测试用例，可以测试一下。

感谢，看起来我如果要是有时间的话 我就可以把这个加密算法实现一下了...

然后用你的test case当Test Vector
