### ISSUE TITLE
[request] Adding .jpg and .raw to compression list

### ISSUE THREAD

**Issue by shaggyze** [regomne/mabi-pack2#4]
#3 
The reason I asked for version and compression as CLI arguments was because it looked like you were using them in IT_VERSION and compress_to_vec_zlib(&stm, 5), but if it's not needed then I guess it's fine.

I was able to lower my uotiara_00001.it down from 70MB to 50MB by adding .jpg and .raw extensions because UO Tiara includes edited HD minimaps and they still work fine in the game.

**Comment by regomne** [comment]
IT_VERSION is the version of the .it format itself, instead of the version of files in it.
Jpg is a compressed format and zlib can barely compress it.
Have added .raw to compression list.

**Comment by shaggyze** [comment]
> Jpg is a compressed format and zlib can barely compress it.
The HD minimaps I use are 4-10MB in size and there are six of that size so adding .jpg helped in compressing saving 5MB, but I suppose it's not enough to warrant adding it.

**Comment by regomne** [comment]
For most jpg files, compressing wastes more cpu but saves few size.

I will add a CLI option to add extra extentisons to compress when I have time.

**Comment by regomne** [comment]
Now support `-f .jpg`
